#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SHIELD_SCENE 2
#define TRANSITION_TIME 0.5

#define PADDLE_COLLISION_BITMASK 0X000001
#define WALL_COLLISION_BITMASK 0X000002
#define BALL_COLLISION_BITMASK 0X000003
#define BRICK_COLLISION_BITMASK 0x000004

#define SCORE_FONT_SIZE 0.1

#endif // __DEFINITIONS_H__
